trigger:
- main

pool:
  vmImage: 'ubuntu-latest' # Or 'windows-latest'

services:
  mssql: 
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    env:
      ACCEPT_EULA: Y
      SA_PASSWORD: Passw0rd!

variables:
  CONNECTIONSTRINGS__TEST_DATABASE: Server=localhost;Database=SocialMedia;User=sa;Password=Passw0rd!;TrustServerCertificate=True;MultipleActiveResultSets=true;

steps:
- bootstrap:
  sh scripts/bootstrap.sh
- build:
  sh scripts/build.sh
- test:
  sh scripts/test.sh
