trigger: none

pr:
- main

name: $(Date:yyyyMMdd)$(Rev:.r)-$(Build.SourceVersion)

pool:
  vmImage: 'ubuntu-latest'

services:
  mssql: 
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    env:
      ACCEPT_EULA: Y
      SA_PASSWORD: Passw0rd!

variables:
  connectionStrings__TestDatabase: Server=localhost;Database=SocialMedia;User=sa;Password=Passw0rd!;TrustServerCertificate=True;MultipleActiveResultSets=true;

steps:
- script: |
    scripts/bootstrap.sh -ci
  displayName: 'Bootstrap'

- script: |
    scripts/build.sh -configuration Release -nobuild
  displayName: '.NET Build'

- script: |
    scripts/test.sh -configuration Release
  displayName: '.NET Test'
