trigger:
  tags:
    include:
    - v*.*

name: $(Build.SourceBranchName).$(Rev:r)

stages:
- stage: BuildAndPublish
  displayName: 'Build and Publish'
  jobs:
  - job: BuildPublishJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: |
        echo "setting version variable from tag (removing "v" prefix)."
        tagName=$(Build.SourceBranchName)
        version=${tagName#v}
        echo "##vso[task.setvariable variable=version]$version"
        echo "version: $version"
      displayName: 'Set version variable'

    - script: |
        scripts/build.sh --configuration Release --version $(version)
      displayName: '.NET Build'

    - script: |
        scripts/publish.sh --configuration Release
      displayName: '.NET Publish'

    - publish: $(System.DefaultWorkingDirectory)/.publish
      artifact: WebApp
      displayName: 'Publish Artifact'

- stage: DeployToQA
  displayName: 'Deploy to QA'
  dependsOn: BuildAndPublish
  condition: succeeded()
  jobs:
  - deployment: DeployToQA
    displayName: 'Deploy WebApp to Azure QA WebApp'
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'QA'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: WebApp
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'Social Media API (Dev)'
              appName: 'agartee-socialmedia-api'
              package: $(Pipeline.Workspace)/WebApp

- stage: DeployToProd
  displayName: 'Deploy to Prod'
  dependsOn: DeployToQA
  condition: succeeded()
  jobs:
  - deployment: DeployToProd
    displayName: 'Deploy WebApp to Azure Production WebApp'
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: WebApp
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'Social Media API (Dev)'
              appName: 'agartee-socialmedia-api'
              package: $(Pipeline.Workspace)/WebApp
