resources:
  pipelines:
    - pipeline: buildTestPublish
      source: 'Portfolio - Social Media Build+Test+Publish'
      trigger:
        branches:
          - main

stages:
  - stage: Dev
    displayName: 'Deploy to Development'
    jobs:
    - deployment: DeployToDev
      displayName: 'Deploy WebApp to Dev Environment'
      environment: 'dev-environment-name'
      strategy:
        runOnce:
          deploy:
            steps:
            - task: AzureWebApp@1
              inputs:
                azureSubscription: 'agartee-socialmedia-api'
                appName: 'agartee-socialmedia-api'
                package: '$(Pipeline.Workspace)/WebApp'

  - stage: QA
    displayName: 'Deploy to QA'
    condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'))
    jobs:
    - deployment: DeployToQA
      displayName: 'Deploy WebApp to QA Environment'
      environment: 'qa-environment-name'
      strategy:
        runOnce:
          deploy:
            steps:
            - task: AzureWebApp@1
              inputs:
                azureSubscription: 'agartee-socialmedia-api'
                appName: 'agartee-socialmedia-api' # same for testing
                package: '$(Pipeline.Workspace)/WebApp'
