resources:
  pipelines:
  - pipeline: buildTestPublish
    source: 'Social Media (Build+Test+Publish)'
    trigger:
      branches:
        include:
        - main

stages:
- stage: DeployToDev
  displayName: 'Deploy to Development Environment'
  jobs:
  - deployment: DeployWebApp
    displayName: 'Deploy WebApp to Azure Web App'
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: buildTestPublish
            artifact: WebApp
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'Social Media (Dev)' # The name of your Azure service connection
              appName: 'agartee-socialmedia-api' # Replace with the name of your Azure Web App
              package: '$(Pipeline.Workspace)/buildTestPublish/WebApp'
