trigger:
  tags:
    include:
    - v*.*

name: $(Build.SourceBranchName):$(Rev:r)

stages:
- stage: BuildAndPublish
  displayName: 'Build and Publish'
  jobs:
  - job: BuildPublishJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        scripts/build.sh --configuration Release
      displayName: '.NET Build'

    - script: |
        scripts/publish.sh --configuration Release
      displayName: '.NET Publish'

    - publish: $(System.DefaultWorkingDirectory)/.publish
      artifact: WebApp
      displayName: 'Publish Artifact'

- stage: DeployToQA
  displayName: 'Deploy to QA'
  dependsOn: BuildAndPublish
  condition: succeeded()
  jobs:
  - deployment: DeployToQA
    displayName: 'Deploy WebApp to Azure QA WebApp'
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'QA'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: WebApp
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'Social Media API (Dev)'
              appName: 'agartee-socialmedia-api'
              package: $(Pipeline.Workspace)/WebApp
