trigger:
  tags:
    include:
    - v*.*

name: $(Date:yyyyMMdd)$(Rev:.r)-$(Build.SourceVersion)

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    scripts/build.sh --configuration Release
  displayName: '.NET Build'

- script: |
    scripts/publish.sh  --configuration Release
  displayName: '.NET Publish'

- publish: $(System.DefaultWorkingDirectory)/.publish
  artifact: WebApp
  displayName: 'Publish Artifact'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Social Media API (Dev)'
    appName: 'agartee-socialmedia-api'
    package: $(System.DefaultWorkingDirectory)/.publish
  displayName: 'Deploy Azure WebApp'
