trigger:
  tags:
    include:
    - v*.*

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: |
    echo "Build.SourceBranch: $(Build.SourceBranch)"
    echo "Build.SourceBranchName: $(Build.SourceBranchName)"
    tagName=$(Build.SourceBranchName)
    echo "##vso[task.setvariable variable=tagName]$tagName"
    echo "Set tagName variable to: $tagName"
  displayName: 'Set and Display tagName variable 1'

- bash: |
    tagName=${BUILD_SOURCEBRANCH#refs/tags/v}
    echo "##vso[task.setvariable variable=tagName]$tagName"
    echo "Set tagName variable to: $tagName"
  displayName: 'Set and Display tagName variable 2'

- bash: |
    version=${$(Build.SourceBranchName)#v}
    echo "Set tagName variable to: $version"
  displayName: 'Set version variable from tag name (removing "v" prefix)'

- bash: |
    echo "Using tagName: $(tagName)"
  displayName: 'Use tagName variable'