trigger:
  tags:
    include:
    - v*.*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    scripts/bootstrap.sh -ci
  displayName: 'Bootstrap'

- script: |
    scripts/build.sh
  displayName: 'Build'

- script: |
    scripts/publish.sh
  displayName: 'Publish'

- bash: |
    echo "Build.SourceBranch: $(Build.SourceBranch)"
    echo "Build.SourceBranchName: $(Build.SourceBranchName)"
    tagName=$(Build.SourceBranchName)
    echo "##vso[task.setvariable variable=tagName]$tagName"
    echo "Set tagName variable to: $tagName"
  displayName: 'Set and Display tagName variable 1'

- bash: |
    tagName=${BUILD_SOURCEBRANCH#refs/tags/}
    echo "##vso[task.setvariable variable=tagName]$tagName"
    echo "Set tagName variable to: $tagName"
  displayName: 'Set and Display tagName variable 2'

- bash: |
    echo "Using tagName: $(tagName)"
  displayName: 'Use tagName variable'