trigger:
  tags:
    include:
    - v*.*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    scripts/bootstrap.sh -ci
  displayName: 'Bootstrap'

- script: |
    scripts/build.sh
  displayName: 'Build'

- script: |
    scripts/publish.sh
  displayName: 'Publish'

- bash: |
    echo "##vso[task.setvariable variable=tagName]$(Build.SourceBranchName)"
  displayName: 'Set tagName variable'
