trigger:
  tags:
    include:
    - v*.*

pool:
  vmImage: 'ubuntu-latest'

steps:

- bash: |
    tagName=$(Build.SourceBranchName)
    version=${tagName#v}
    echo "Set version variable to: $version"
  displayName: 'Set version variable from tag name (removing "v" prefix)'

- bash: |
    echo "Using tagName: $(tagName)"
  displayName: 'Use tagName variable'
